export const songLyrics = [
    {"time": 2.81, "text": "Yeah"},
    {"time": 6.74, "text": "And you say Chi City"},
    {"time": 9.80, "text": "Chi City, Chi City"},
    {"time": 12.54, "text": "I'm comin' home again"},
    {"time": 14.42, "text": "Do you think about me now and then? (Yeah)"},
    {"time": 17.17, "text": "Do you think about me now and then?"},
    {"time": 20.61, "text": "'Cause I'm comin' home again, 'min' home again"},
    {"time": 25.03, "text": "I met this girl when I was three years old"},
    {"time": 27.92, "text": "And what I loved most, she had so much soul"},
    {"time": 30.13, "text": "She said, excuse me, little homie, I know you don't know me"},
    {"time": 33.11, "text": "But, my name is Wendy and I like to blow trees"},
    {"time": 36.35, "text": "And from that point I never blow her off"},
    {"time": 38.38, "text": "Niggas come from outta town, I like to show her off"},
    {"time": 41.40, "text": "They like to act tough, she like to tow 'em off"},
    {"time": 44.08, "text": "And make 'em straighten up their act 'cause she know they soft"},
    {"time": 46.68, "text": "And when I grew up, she showed me how to go downtown"},
    {"time": 49.75, "text": "In the night time her face lit up, so astoundin'"},
    {"time": 52.64, "text": "And I told her in my heart is where she always be"},
    {"time": 55.19, "text": "She never mess with entertainers 'cause they always leave"},
    {"time": 57.94, "text": "She said it felt like they walked and drove on me"},
    {"time": 60.41, "text": "Knew I was gang affiliated, got on TV and told on me"},
    {"time": 63.69, "text": "I guess it's why last winter she got so cold on me"},
    {"time": 66.55, "text": "She said, 'Ye keep makin' that (I'm comin' home again)"},
    {"time": 68.12, "text": "Keep makin' that platinum and gold for me"},
];
